language: python
python:
  - 3.8
dist: bionic
services:
  - docker
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
  chrome: stable
before_install:
  - docker-compose build
install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - mkdir geckodriver
  - tar xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
  - export PATH=$(pwd)/geckodriver:$PATH
  - wget https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
  - mkdir chromedriver
  - unzip chromedriver_linux64.zip -d chromedriver
  - export PATH=$(pwd)/chromedriver:$PATH
  - pip install -r requirements/development.txt
script: pytest
