language: python
python:
  - 3.8
services:
  - docker
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
  apt:
    packages:
      - firefox-geckodriver
before_install:
  - docker build -t python-server:latest .
install:
  - pip install -r requirements/development.txt
script: pytest
