version: '3'
services:
  web:
    container_name: "python-server"
    build: .
    ports:
      - "5000:5000"
  database:
    container_name: "postgres"
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
